### ISSUE TITLE
Compatibility with latest Aseprite version.

### ISSUE THREAD

**Issue by ghost** [BoThompson/pixeLips#1]
The script did not work for me in the latest Aseprite version.
The function ```findLayer()``` was not working properly, and I constantly got a message "AI layer is missing from the group.", even though I had an appropriately named layer in the correct group layer.
I fixed the function by making it search for the layers inside of the parent instead of searching in layers of sprite and checking if a parent of a layer is the correct one. (I also fixed all of the calls to the function to work with the new code)
I may be wrong about it, but the problem might be that Aseprite api for sprite.layers may not include layers inside of groups.
Feel free to ask me for more details, just as well as to ignore this issue completely.

**Comment by agamavinda23** [comment]
hi,i had the same problem can u help step by step to fix this?

**Comment by ghost** [comment]
Hi, I haven't used it at all, because I only tried to fix pixeLisp for my friend, but there is a chance that this version I made some time ago will work:

[pixeLips.zip](https://github.com/BoThompson/pixeLips/files/11966693/pixeLips.zip)

**Comment by agamavinda23** [comment]
Thanks u so much,i will try it,
But i have fixed this issue,

But thanks for ur feeeback 🙏🏻

Pada tanggal Kam, 6 Jul 2023 16.25, Ybaedbaenn ***@***.***>
menulis:

**Comment by Ybaedbaenn** [comment]
Since the issue did not receive any response from the code owner, and the code is not being actively maintained, I'm closing the issue.

**Comment by Ybaedbaenn** [comment]
Since the issue did not receive any response from the code owner, and the code is not being actively maintained, I'm closing the issue.

**Comment by Ybaedbaenn** [comment]
Since the issue did not receive any response from the code owner, and the code is not being actively maintained, I'm closing the issue.

**Comment by ghost** [comment]
Since the issue did not receive any response from the code owner, and the code is not being actively maintained, I'm closing the issue.
